remote_theme: "coderua/infotorg-api-jekyll-theme@main"
# --- Jekyll configuration ---
plugins:
  # See the documentation for Jekyll SEO Tag: https://github.com/jekyll/jekyll-seo-tag
  - jekyll-seo-tag
